use anyhow::Result;
use reqwest::Client;

pub struct SlmPayload {
    pub req: String,
    pub res: Option<String>,
}

pub struct SlmClient {
    pub url: String,
    pub sys_prompt: String,
}

impl SlmClient {
    pub fn new(url: String) -> Self {
        let sys_prompt = "you are general purpose LLM, that I am using for language processing.
        There is going to be a specific format in which we will converse. I will send in the req in json format,
        and the res should also be in the json format. See the formats below.

        You will always the receive the prompt in this schema:
        {\"prompt\": \"prompt_sent_by_the_user\"}

        And your response should be exactly in this schema:
        {\"res\": \"response generated by you\"}
        Do not include markdown blocks, text wrappers, or trailing characters outside the raw JSON structure.
        
        So now the req is next."
        .to_string();

        Self { url, sys_prompt }
    }

    pub async fn converse(&self, prompt: &str) -> Result<String> {
        let client = Client::new();
        let combined_prompt = format!("{}\n\nprompt: {}\n\nJSON Output:", self.sys_prompt, prompt);

        let payload = serde_json::json!({
            "model": "qwen2.5:1.5b".to_string(),
            "prompt": combined_prompt,
            "stream": false,
            "options": {
                "temperature": 0.0 // Eliminate non-deterministic randomness
            }
        });

        let response = client
            .post(format!("{}/api/generate", self.url))
            .json(&payload)
            .send()
            .await?;

        let body: serde_json::Value = response.json().await?;
        let raw_text = body["response"].as_str().unwrap_or("").trim();

        let clean_json = raw_text
            .strip_prefix("```json")
            .unwrap_or(raw_text)
            .strip_suffix("```")
            .unwrap_or(raw_text)
            .trim();

        Ok(clean_json.to_string())
    }
}
